project_id = "cxfywiqnylxsdyeesfdb"

[functions.configure-linkedin-auth]
verify_jwt = false

[functions.ai-match]
verify_jwt = false

[functions.linkedin-auth]
verify_jwt = false

[functions.dev-login]
verify_jwt = false

[functions.seed-profiles]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.weekly-intro-match]
verify_jwt = false

[functions.linkedin-share]
verify_jwt = false

[functions.delete-user]
verify_jwt = false