import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { code, redirectUri, forceSync } = await req.json();

    if (!code) {
      return new Response(JSON.stringify({ error: 'Authorization code is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const LINKEDIN_CLIENT_ID = Deno.env.get('LINKEDIN_CLIENT_ID');
    const LINKEDIN_CLIENT_SECRET = Deno.env.get('LINKEDIN_CLIENT_SECRET');
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!LINKEDIN_CLIENT_ID || !LINKEDIN_CLIENT_SECRET) {
      console.error('Missing LinkedIn credentials');
      return new Response(JSON.stringify({ error: 'LinkedIn credentials not configured' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Exchange authorization code for access token
    console.log('Exchanging code for access token...');
    const tokenResponse = await fetch('https://www.linkedin.com/oauth/v2/accessToken', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        grant_type: 'authorization_code',
        code,
        redirect_uri: redirectUri,
        client_id: LINKEDIN_CLIENT_ID,
        client_secret: LINKEDIN_CLIENT_SECRET,
      }),
    });

    if (!tokenResponse.ok) {
      const errorText = await tokenResponse.text();
      console.error('Token exchange failed:', errorText);
      return new Response(JSON.stringify({ error: 'Failed to exchange authorization code' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const tokenData = await tokenResponse.json();
    const accessToken = tokenData.access_token;
    console.log('Access token obtained');

    // Fetch user profile from LinkedIn userinfo endpoint (OIDC)
    console.log('Fetching LinkedIn profile from /v2/userinfo...');
    const profileResponse = await fetch('https://api.linkedin.com/v2/userinfo', {
      headers: {
        'Authorization': `Bearer ${accessToken}`,
      },
    });

    if (!profileResponse.ok) {
      const errorText = await profileResponse.text();
      console.error('Profile fetch failed:', errorText);
      return new Response(JSON.stringify({ error: 'Failed to fetch LinkedIn profile' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const profileData = await profileResponse.json();
    console.log('LinkedIn /v2/userinfo response:', JSON.stringify(profileData));

    // Fetch /v2/me with geoLocation projection for location data
    console.log('Trying LinkedIn /v2/me endpoint with geoLocation projection...');
    const meResponse = await fetch('https://api.linkedin.com/v2/me?projection=(vanityName,headline,localizedHeadline,geoLocation(geo~,autoGenerated))', {
      headers: {
        'Authorization': `Bearer ${accessToken}`,
      },
    });
    
    let vanityName: string | null = null;
    let linkedinHeadline: string | null = null;
    let linkedinLocation: string | null = null;
    if (meResponse.ok) {
      const meData = await meResponse.json();
      console.log('LinkedIn /v2/me response:', JSON.stringify(meData));
      vanityName = meData.vanityName || null;
      
      // Extract headline with localization support (r_liteprofile provides localized data)
      if (meData.headline) {
        if (typeof meData.headline === 'string') {
          linkedinHeadline = meData.headline;
        } else if (meData.headline.localized) {
          // Get the preferred locale or fallback to en_US
          const preferredLocale = meData.headline.preferredLocale;
          const localeKey = preferredLocale 
            ? `${preferredLocale.language}_${preferredLocale.country}`
            : 'en_US';
          linkedinHeadline = meData.headline.localized[localeKey] || 
                            meData.headline.localized['en_US'] || 
                            Object.values(meData.headline.localized)[0] as string || null;
        }
      }
      // Also check localizedHeadline field (r_liteprofile format)
      if (!linkedinHeadline && meData.localizedHeadline) {
        linkedinHeadline = meData.localizedHeadline;
      }
      
      // Extract location from geoLocation projection
      if (meData.geoLocation && meData.geoLocation['geo~']) {
        const geo = meData.geoLocation['geo~'];
        // Build location string from available geo data
        const locationParts: string[] = [];
        if (geo.defaultLocalizedName?.value) {
          linkedinLocation = geo.defaultLocalizedName.value;
        } else if (geo.country?.defaultLocalizedName?.value && geo.city?.defaultLocalizedName?.value) {
          linkedinLocation = `${geo.city.defaultLocalizedName.value}, ${geo.country.defaultLocalizedName.value}`;
        } else if (geo.defaultLocalizedNameWithoutCountryName) {
          linkedinLocation = geo.defaultLocalizedNameWithoutCountryName;
        }
        console.log('Extracted location:', linkedinLocation);
      }
    } else {
      const meError = await meResponse.text();
      console.log('LinkedIn /v2/me failed:', meError);
    }

    // Try to fetch skills with r_fullprofile scope
    let linkedinSkills: string[] = [];
    console.log('Trying LinkedIn /v2/me/skills endpoint...');
    const skillsResponse = await fetch('https://api.linkedin.com/v2/me/skills?projection=(elements*(id,name))', {
      headers: {
        'Authorization': `Bearer ${accessToken}`,
      },
    });
    
    if (skillsResponse.ok) {
      const skillsData = await skillsResponse.json();
      console.log('LinkedIn /v2/me/skills response:', JSON.stringify(skillsData));
      if (skillsData.elements && Array.isArray(skillsData.elements)) {
        linkedinSkills = skillsData.elements
          .map((s: { name?: string }) => s.name)
          .filter((name: string | undefined): name is string => !!name);
      }
      console.log('Extracted skills:', linkedinSkills);
    } else {
      const skillsError = await skillsResponse.text();
      console.log('LinkedIn /v2/me/skills failed:', skillsError);
    }

    const email = profileData.email;
    const fullName = profileData.name;
    const avatarUrl = profileData.picture;
    const linkedinSub = profileData.sub;
    const linkedinUrl = vanityName ? `https://linkedin.com/in/${vanityName}` : null;

    if (!email) {
      return new Response(JSON.stringify({ error: 'Email not available from LinkedIn' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Create Supabase admin client
    const supabaseAdmin = createClient(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    });

    // Check if user exists
    const { data: existingUsers, error: listError } = await supabaseAdmin.auth.admin.listUsers();
    
    let userId: string;
    let isNewUser = false;

    const existingUser = existingUsers?.users?.find(u => u.email === email);

    if (existingUser) {
      userId = existingUser.id;
      console.log('Existing user found:', userId);
      
      // Update user metadata
      await supabaseAdmin.auth.admin.updateUserById(userId, {
        user_metadata: {
          full_name: fullName,
          avatar_url: avatarUrl,
          linkedin_id: linkedinSub,
          provider: 'linkedin',
        },
      });
    } else {
      // Create new user
      console.log('Creating new user...');
      const { data: newUser, error: createError } = await supabaseAdmin.auth.admin.createUser({
        email,
        email_confirm: true,
        user_metadata: {
          full_name: fullName,
          avatar_url: avatarUrl,
          linkedin_id: linkedinSub,
          provider: 'linkedin',
        },
      });

      if (createError) {
        console.error('User creation failed:', createError);
        return new Response(JSON.stringify({ error: 'Failed to create user' }), {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }

      userId = newUser.user.id;
      isNewUser = true;
      console.log('New user created:', userId);

      // Create initial profile with LinkedIn data including avatar, URL, headline, location, and skills
      const { error: profileError } = await supabaseAdmin.from('profiles').insert({
        user_id: userId,
        full_name: fullName,
        email: email,
        avatar_url: avatarUrl,
        linkedin_url: linkedinUrl,
        headline: linkedinHeadline,
        location: linkedinLocation,
        skills: linkedinSkills.length > 0 ? linkedinSkills : null,
      });

      if (profileError) {
        console.error('Profile creation failed:', profileError);
        // Don't fail the auth flow, profile can be created later
      } else {
        console.log('Profile created with LinkedIn data (avatar, URL, headline, location, skills)');
      }
    }
    
    // For existing users, update avatar, linkedin_url, headline, location, and skills
    // If forceSync is true, always update. Otherwise only update if empty.
    if (!isNewUser) {
      const { data: existingProfile } = await supabaseAdmin
        .from('profiles')
        .select('avatar_url, linkedin_url, headline, location, skills')
        .eq('user_id', userId)
        .maybeSingle();
      
      if (existingProfile) {
        const updates: Record<string, string | string[]> = {};
        if ((forceSync || !existingProfile.avatar_url) && avatarUrl) {
          updates.avatar_url = avatarUrl;
        }
        if ((forceSync || !existingProfile.linkedin_url) && linkedinUrl) {
          updates.linkedin_url = linkedinUrl;
        }
        if ((forceSync || !existingProfile.headline) && linkedinHeadline) {
          updates.headline = linkedinHeadline;
        }
        if ((forceSync || !existingProfile.location) && linkedinLocation) {
          updates.location = linkedinLocation;
        }
        if ((forceSync || !existingProfile.skills || existingProfile.skills.length === 0) && linkedinSkills.length > 0) {
          updates.skills = linkedinSkills;
        }
        if (Object.keys(updates).length > 0) {
          await supabaseAdmin
            .from('profiles')
            .update(updates)
            .eq('user_id', userId);
          console.log('Updated existing profile with LinkedIn data:', Object.keys(updates), forceSync ? '(force sync)' : '');
        }
      }
    }

    // Generate a session for the user using magic link approach
    const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
      type: 'magiclink',
      email,
    });

    if (linkError) {
      console.error('Link generation failed:', linkError);
      return new Response(JSON.stringify({ error: 'Failed to generate session' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Extract the token from the link
    const linkUrl = new URL(linkData.properties.action_link);
    const token = linkUrl.searchParams.get('token');
    const type = linkUrl.searchParams.get('type');

    return new Response(JSON.stringify({
      success: true,
      token,
      type,
      isNewUser,
      user: {
        id: userId,
        email,
        fullName,
        avatarUrl,
      },
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('LinkedIn auth error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Internal server error';
    return new Response(JSON.stringify({ error: errorMessage }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
