-- Timeslot confirmations: users reconfirm each week
CREATE TABLE IF NOT EXISTS public.timeslot_confirmations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  timeslot_id uuid NOT NULL REFERENCES public.group_timeslots(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_of date NOT NULL, -- The Monday of the week this confirmation is for
  confirmed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(timeslot_id, user_id, week_of)
);

-- Group matches: 1:1 pairings generated by the scheduler
CREATE TABLE IF NOT EXISTS public.group_matches (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  group_id uuid NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  timeslot_id uuid NOT NULL REFERENCES public.group_timeslots(id) ON DELETE CASCADE,
  user_a_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_b_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_of date NOT NULL, -- The Monday of the week
  match_reason text, -- AI-generated reason why they're matched
  video_call_url text,
  status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'skipped')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(timeslot_id, user_a_id, week_of),
  UNIQUE(timeslot_id, user_b_id, week_of)
);

-- RLS
ALTER TABLE public.timeslot_confirmations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_matches ENABLE ROW LEVEL SECURITY;

-- Confirmations: users manage their own
CREATE POLICY "Users can view their confirmations" ON public.timeslot_confirmations
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Members can view group confirmations" ON public.timeslot_confirmations
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.group_timeslots gt
      JOIN public.group_members gm ON gm.group_id = gt.group_id
      WHERE gt.id = timeslot_confirmations.timeslot_id AND gm.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can confirm" ON public.timeslot_confirmations
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can unconfirm" ON public.timeslot_confirmations
  FOR DELETE USING (auth.uid() = user_id);

-- Matches: participants can view their matches
CREATE POLICY "Users can view their matches" ON public.group_matches
  FOR SELECT USING (auth.uid() = user_a_id OR auth.uid() = user_b_id);

CREATE POLICY "Members can view group matches" ON public.group_matches
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.group_members gm
      WHERE gm.group_id = group_matches.group_id AND gm.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update their match status" ON public.group_matches
  FOR UPDATE USING (auth.uid() = user_a_id OR auth.uid() = user_b_id);

-- Indexes
CREATE INDEX idx_timeslot_confirmations_timeslot ON public.timeslot_confirmations(timeslot_id, week_of);
CREATE INDEX idx_timeslot_confirmations_user ON public.timeslot_confirmations(user_id, week_of);
CREATE INDEX idx_group_matches_users ON public.group_matches(user_a_id, week_of);
CREATE INDEX idx_group_matches_users_b ON public.group_matches(user_b_id, week_of);
CREATE INDEX idx_group_matches_timeslot ON public.group_matches(timeslot_id, week_of);
CREATE INDEX idx_group_matches_group ON public.group_matches(group_id, week_of);
